negative_prompt: "worst quality, low quality, early, score_1, score_2, score_3, cartoon, graphic, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, long body, bad anatomy, bad hands, missing fingers, extra fingers, extra digits, fewer digits, cropped, very displeasing, artist name, blurry, jpeg artifacts, lowres, censor, twins, duplicate"
steps: 32
width: 896
height: 1152
cfg_scale: 4
sampler: "ER SDE"
scheduler: "beta"
seed: -1
batch_count: 1
batch_size: 1
override_settings:
  sd_model_checkpoint: "anima_2_9_Anima-2.9B-preview-v1"
  forge_additional_modules:
    - "qwen_image_vae.safetensors"
    - "qwen_3_06b_base.safetensors"
alwayson_scripts:
  ADetailer:
    args:
      - true
      - false
      - ad_model: face_yolov8n.pt
        ad_denoising_strength: 0.4
        ad_inpaint_only_masked: true
